safe-civilians: false
tag:
    default-color: '8'
    max-length: 5
    bracket:
        color: '8'
        leader-color: '4'
        left: ''
        right: ''
    min-length: 2
    separator:
        color: '8'
        leader-color: '4'
        char: ' .'
settings:
    online-mode: true
    disable-messages: false
    tameable-mobs-sharing: false
    teleport-blocks: false
    teleport-home-on-spawn: false
    drop-items-on-clan-home: false
    keep-items-on-clan-home: false
    item-list: []
    show-debug-info: false
    mchat-integration: true
    enable-auto-groups: false
    chat-compatibility-mode: true
    rival-limit-percent: 50
    use-colorcode-from-prefix-for-name: true
    display-chat-tags: true
    unrivable-clans:
    - admin
    - staff
    - mod
    show-unverified-on-list: false
    blacklisted-worlds: []
    banned-players: []
    disallowed-tags:
    - vip
    - clan
    language: en
    disallowed-tag-colors:
    - '4'
    server-name: '&4SimpleClans'
    new-clan-verification-required: true
    allow-regroup-command: true
spout:
    in-game-tags: true
    alert-url: ''
    default-cape-url: http://i.imgur.com/pjqV6.png
    enable-clan-capes: true
    in-game-tags-colored: false
commands:
    more: more
    ally: ally
    clan: clan
    accept: accept
    deny: deny
    global: global
    force-priority: true
economy:
    creation-price: 100.0
    purchase-clan-create: false
    verification-price: 1000.0
    purchase-clan-verify: false
    invite-price: 20.0
    purchase-clan-invite: false
    home-teleport-price: 5.0
    purchase-home-teleport: false
    home-teleport-set-price: 5.0
    purchase-home-teleport-set: false
    money-per-kill: false
    money-per-kill-kdr-multipier: 10
kill-weights:
    rival: 2.0
    civilian: 0.0
    neutral: 1.0
clan:
    homebase-teleport-wait-secs: 10
    homebase-can-be-set-only-once: true
    min-size-to-set-rival: 3
    max-length: 25
    confirmation-for-promote: false
    trust-members-by-default: false
    confirmation-for-demote: false
    ff-on-by-default: false
    min-length: 2
    min-size-to-set-ally: 3
page:
    untrusted-color: '8'
    clan-name-color: b
    subtitle-color: '7'
    headings-color: '8'
    trusted-color: f
    leader-color: '4'
    separator: '-'
    size: 100
clanchat:
    rank.color: e
    tag-based-clan-chat: false
    name-color: e
    player-bracket:
        left: '<'
        right: '>'
    announcement-color: e
    message-color: b
    tag-bracket:
        color: e
        left: '['
        right: ']'
    enable: true
request:
    message-color: b
    ask-frequency-secs: 60
    max-asks-per-request: 1440
bb:
    color: e
    accent-color: '8'
    show-on-login: true
    size: 6
allychat:
    tag-color: b
    name-color: f
    player-bracket:
        left: <
        right: '>'
    message-color: '3'
    tag-bracket:
        color: '8'
        left: '['
        right: ']'
    enable: true
purge:
    inactive-player-data-days: 30
    inactive-clan-days: 7
    unverified-clan-days: 2
mysql:
    username: ''
    host: localhost
    enable: false
    password: ''
    database: ''
permissions:
  auto-group-groupname: true
  YourClanNameHere:
  - test.permission
performance:
  use-threads: false
  use-bungeecord: false
